### ISSUE TITLE
GPT Score 출력에 모델 이름 키 값 추가

### ISSUE THREAD

**Issue by TAK-C** [KMOU-NLP-Lab/DeuChatbot#43]
## 📝 Description
```json
{
    "1": 100,
    "2": 100,
    "3": 100,
    "average": 75.64
}
```
**위의 기존 JSON 포맷을 아래와 같이 변경(모델이름 키 값 추가)**
```json
{
   "모델 이름":{
         "1": 100,
         "2": 100,
         "3": 100,
         "average": 75.64       
    }
}
```

## 📍 Todo
- [x]  'A' 열에서 모델 이름 추출 하여 키 값으로 추가
- [x]  모델 이름의 변화를 기준으로 출력을 구분 할 수 있도록 코드 수정
- [x]  출력된 GPT Score 평균값 중 가장 큰 값을 가지는 경우에 대하여 {"모델이름&청크"}:{"점수"} 출력

## 📢 To Reviewers
@effort-type

**Comment by effort-type** [comment]
정상적으로 동작하는 거 확인했습니다. 기존 코드는 수정하지 않으면서 기능을 추가 및 수정할 수 있도록 변경해서 제가 다시 push 하겠습니다.
